ALTER TABLE users
  ADD COLUMN firstname VARCHAR(50) DEFAULT NULL,
  ADD COLUMN lastname VARCHAR(50) DEFAULT NULL,
  ADD COLUMN dateofbirth DATE DEFAULT NULL,
  ADD COLUMN sex VARCHAR(10) DEFAULT NULL,
  ADD COLUMN height INT DEFAULT NULL,
  ADD COLUMN nationality VARCHAR(50) DEFAULT NULL;
